import './es6-promise'
import './vue-class-component'
import './vue-feathers'
import './vue-form-generator'
import './vue-markdown'
import './vue-material'
import './vue-portal'
import './vue-touch'
import './vuelidate'
// import './form-schema-native'
import './vue-mdc-adapter'
