export { Base } from '@/domain/spell-components/base'
export { Component } from '@/domain/spell-components/component'
export { Descriptor } from '@/domain/spell-components/descriptor'
export { Duration, TimedDuration } from '@/domain/spell-components/duration'
export { Effect, AreaEffect, AreaFormat, AreaType } from '@/domain/spell-components/effect'
export { Range, RangeWithDistance } from '@/domain/spell-components/range'
export { Resolve } from '@/domain/spell-components/resolve'
